name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - run: ./deploy-scripts/01-lint.sh
      - run: ./deploy-scripts/02-build.sh
      - run: ./deploy-scripts/03-run-tests.sh
